name: urunlerapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  flutter_slidable: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Bu satırı ekle

flutter:

  uses-material-design: true

  assets:
    - assets/store.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/store.png"
